services:
  kong:
    image: kong:latest
    container_name: global-kong-gateway
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml:ro
    ports:
      - "8000:8000" # HTTP Proxy Listener
      - "8443:8443" # HTTPS Proxy Listener
      - "8001:8001" # Admin API (Read-only dalam DB-less mode)
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - default
      - global-network-geosandbox

networks:
  default:
  global-network-geosandbox:
    external: true
