services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: global-swagger-ui
    restart: always
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /schema/swagger.yaml
    volumes:
      - ./swagger.yaml:/schema/swagger.yaml
