services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: global-jenkins-cicd
    restart: on-failure
    ports:
      - "8780:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - default
      - global-network-geosandbox

volumes:
  jenkins_data:

networks:
  default:
  global-network-geosandbox:
    external: true